### PR TITLE
Add sort-imports-es6-autofix plugin for eslint

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://github.com/brianchandotcom/liferay-portal/pull/67187#issuecomment-457673237

### CODE REVIEW

**Comment by jbalsas** [comment]
I think the errors have something to do with https://github.com/nodejs/node/issues/19786, but I'm still not sure how to fix this... trying to figure this out...

**Comment by jbalsas** [comment]
Looks like this is passing now... @bryceosterhaus, is there an option to add some tests to verify this is working as expected?

**Comment by jbalsas** [comment]
Actually... it seems there are 3 errors but Travis is not getting ahold of them... I don't think they're related to this, though...

```
  383 passing (2s)
  3 failing
```

**Comment by bryceosterhaus** [comment]
@jbalsas yeah I can add some tests for it. Ill let you know when I add them

**Pull request merged**
