### PR TITLE
Fix regex

### PR DESCRIPTION
**Pull request by ling-alan-huang**
@natecavanaugh,

I forwarded this issue via mail.
The regex breaks some JS files, could you please review my changes?

One more thing, could you tell me how to run the test for this repo on my local?

Thanks.

### CODE REVIEW

**Comment by jbalsas** [comment]
This is green now, although there are errors in the log, probably unrelated in any case!

```
  383 passing (2s)
  3 failing
```

**Comment by bryceosterhaus** [comment]
Only concern I see with this is the lack of support for negative lookbehind regex in node.js for versions below 9. v6 through v8 requires a flag.

https://node.green/#ES2018-features--RegExp-Lookbehind-Assertions

@jbalsas is this an issue for this project?

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, that's a nice catch!

We currently have the following tests green:

screen shot 2019-02-01 at 10 08 30

Might we be lacking some tests, since something shouldn't be properly working for the older node versions?

This is definitely a concern, since we're currently using `8.4.0`, but we could try moving to 10... I'll ping @petershin about this.

**Comment by natecavanaugh** [comment]
@ling-alan-huang Run `gulp test-coverage` to check the tests and the coverage. Any change should keep the coverage at 100%.

I'll go ahead and review this one :)

**Comment by natecavanaugh** [comment]
Hey guys,
Okay, a few thoughts...
1. As @bryceosterhaus mentioned, backward regexes need a flag, so if we can't find another way to do this via plain regex, we may want to modify the bin/index.js file with this http://sambal.org/2014/02/passing-options-node-shebang-line/
2. It appears that the tests weren't running before, but this change both fixes that, but nulls out certain lines, which we shouldn't do. Basically, it appears that the bug is that it is grabbing words where `try` (or a keyword) is being yanked out. So, I think the test should reflect that to be a tad bit more generalized (we could say make the string something like `'partOfAStringEntry(key)', just to make it more obvious later on).

Is there anything I'm missing?

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, @natecavanaugh, we upgraded portal to Node10, and being the most important client, I think we can simply merge this for now. 

We can up the node requirement in `package.json` to mark that there's some feature not exactly working as expected if that was a concern...

What do you think?

**Comment by bryceosterhaus** [comment]
Sounds good to me. I'll verify the tests are working and once that is good to go I will merge and publish.

**Pull request merged**
