### PR TITLE
Fix regex

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@natecavanaugh, see https://github.com/brianchandotcom/liferay-portal/pull/61820

**Comment by natecavanaugh** [comment]
Thanks Hugo, you can look for my reasons on my changes on 1816e62 :)

**Comment by jbalsas** [comment]
Hey @natecavanaugh, could you please release a new version so we can update the usage?

Thanks!

**Comment by natecavanaugh** [comment]
Whoops, sorry guys, just now seeing this comment. I'll release a new version :)

**Comment by natecavanaugh** [comment]
K, done :) Thanks guys!

**Pull request closed without merging**
